"""
setup_multilang.py
Run this once in your project root:  python setup_multilang.py
It will create/overwrite all multilingual support files with correct content.
"""
import os, pathlib

ROOT = pathlib.Path(__file__).parent

files = {}

# ── utils/i18n.py ─────────────────────────────────────────────────────────────
files["utils/i18n.py"] = (
    "from __future__ import annotations\n"
    "\n"
    "import json\n"
    "import logging\n"
    "from pathlib import Path\n"
    "\n"
    "logger = logging.getLogger(__name__)\n"
    "\n"
    "SUPPORTED_LANGUAGES = (\"en\", \"ar\", \"ru\")\n"
    "DEFAULT_LANGUAGE = \"en\"\n"
    "\n"
    "_translations: dict[str, dict[str, str]] = {}\n"
    "\n"
    "\n"
    "def _find_locale_file(lang: str) -> Path | None:\n"
    "    here = Path(__file__).resolve().parent.parent\n"
    "    cwd = Path.cwd()\n"
    "    candidates = [\n"
    "        here / \"locales\" / (lang + \".json\"),\n"
    "        cwd  / \"locales\" / (lang + \".json\"),\n"
    "        here / (lang + \".json\"),\n"
    "        cwd  / (lang + \".json\"),\n"
    "    ]\n"
    "    for path in candidates:\n"
    "        if path.is_file():\n"
    "            return path\n"
    "    return None\n"
    "\n"
    "\n"
    "def load_translations() -> None:\n"
    "    for lang in SUPPORTED_LANGUAGES:\n"
    "        path = _find_locale_file(lang)\n"
    "        if path is None:\n"
    "            logger.warning(\"Locale file not found for: %s\", lang)\n"
    "            _translations[lang] = {}\n"
    "            continue\n"
    "        try:\n"
    "            with path.open(encoding=\"utf-8\") as fh:\n"
    "                _translations[lang] = json.load(fh)\n"
    "        except Exception as exc:\n"
    "            logger.error(\"Failed to load locale %s: %s\", lang, exc)\n"
    "            _translations[lang] = {}\n"
    "\n"
    "\n"
    "def t(lang, key, **kwargs):\n"
    "    effective = lang if lang in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE\n"
    "    text = (\n"
    "        _translations.get(effective, {}).get(key)\n"
    "        or _translations.get(DEFAULT_LANGUAGE, {}).get(key)\n"
    "        or key\n"
    "    )\n"
    "    if kwargs:\n"
    "        try:\n"
    "            text = text.format_map(kwargs)\n"
    "        except (KeyError, ValueError):\n"
    "            pass\n"
    "    return text\n"
    "\n"
    "\n"
    "load_translations()\n"
)

# ── services/user_store.py ────────────────────────────────────────────────────
files["services/user_store.py"] = (
    "from __future__ import annotations\n"
    "\n"
    "import json\n"
    "import logging\n"
    "from pathlib import Path\n"
    "\n"
    "logger = logging.getLogger(__name__)\n"
    "\n"
    "_USERS_FILE = Path(\"./data/all_users.json\")\n"
    "_languages: dict[int, str] = {}\n"
    "_all_users: set[int] = set()\n"
    "\n"
    "\n"
    "def _load() -> None:\n"
    "    try:\n"
    "        _STORE_FILE.parent.mkdir(parents=True, exist_ok=True)\n"
    "        if _STORE_FILE.exists():\n"
    "            raw = json.loads(_STORE_FILE.read_text(encoding=\"utf-8\"))\n"
    "            _languages.update({int(k): v for k, v in raw.items()})\n"
    "    except Exception as exc:\n"
    "        logger.warning(\"Could not load user language store: %s\", exc)\n"
    "    try:\n"
    "        if _USERS_FILE.exists():\n"
    "            raw2 = json.loads(_USERS_FILE.read_text(encoding=\"utf-8\"))\n"
    "            _all_users.update(int(u) for u in raw2)\n"
    "    except Exception as exc:\n"
    "        logger.warning(\"Could not load all-users store: %s\", exc)\n"
    "\n"
    "\n"
    "def _save() -> None:\n"
    "    try:\n"
    "        _STORE_FILE.parent.mkdir(parents=True, exist_ok=True)\n"
    "        _STORE_FILE.write_text(\n"
    "            json.dumps({str(k): v for k, v in _languages.items()}, ensure_ascii=False),\n"
    "            encoding=\"utf-8\",\n"
    "        )\n"
    "    except Exception as exc:\n"
    "        logger.warning(\"Could not save user language store: %s\", exc)\n"
    "\n"
    "\n"
    "def _save_users() -> None:\n"
    "    try:\n"
    "        _USERS_FILE.parent.mkdir(parents=True, exist_ok=True)\n"
    "        _USERS_FILE.write_text(\n"
    "            json.dumps(list(_all_users), ensure_ascii=False),\n"
    "            encoding=\"utf-8\",\n"
    "        )\n"
    "    except Exception as exc:\n"
    "        logger.warning(\"Could not save all-users store: %s\", exc)\n"
    "\n"
    "\n"
    "def register_user(user_id: int) -> None:\n"
    "    if user_id not in _all_users:\n"
    "        _all_users.add(user_id)\n"
    "        _save_users()\n"
    "\n"
    "\n"
    "def get_all_user_ids() -> list[int]:\n"
    "    return list(_all_users)\n"
    "\n"
    "\n"
    "def user_count() -> int:\n"
    "    return len(_all_users)\n"
    "\n"
    "\n"
    "def get_user_lang(user_id: int):\n"
    "    return _languages.get(user_id)\n"
    "\n"
    "\n"
    "def get_user_lang_or_default(user_id: int, default: str = \"en\") -> str:\n"
    "    return _languages.get(user_id) or default\n"
    "\n"
    "\n"
    "def set_user_lang(user_id: int, lang: str) -> None:\n"
    "    _languages[user_id] = lang\n"
    "    _save()\n"
    "\n"
    "\n"
    "def has_chosen_language(user_id: int) -> bool:\n"
    "    return user_id in _languages\n"
    "\n"
    "\n"
    "_load()\n"
)

# ── handlers/common.py ────────────────────────────────────────────────────────
files["handlers/common.py"] = (
    "from __future__ import annotations\n"
    "\n"
    "import uuid\n"
    "from collections import OrderedDict\n"
    "\n"
    "from aiogram.types import InlineKeyboardMarkup\n"
    "from aiogram.utils.keyboard import InlineKeyboardBuilder\n"
    "\n"
    "from utils.i18n import t\n"
    "\n"
    "_URL_STORE: OrderedDict[str, str] = OrderedDict()\n"
    "_URL_STORE_MAX = 500\n"
    "\n"
    "\n"
    "def _store_url(url: str) -> str:\n"
    "    token = uuid.uuid4().hex[:12]\n"
    "    _URL_STORE[token] = url\n"
    "    if len(_URL_STORE) > _URL_STORE_MAX:\n"
    "        _URL_STORE.popitem(last=False)\n"
    "    return token\n"
    "\n"
    "\n"
    "def resolve_url(token: str):\n"
    "    return _URL_STORE.get(token)\n"
    "\n"
    "\n"
    "def quality_keyboard(url: str, lang: str = \"en\") -> InlineKeyboardMarkup:\n"
    "    token = _store_url(url)\n"
    "    builder = InlineKeyboardBuilder()\n"
    "    builder.button(text=t(lang, \"btn_best\"),  callback_data=\"quality:best:\"  + token)\n"
    "    builder.button(text=t(lang, \"btn_720p\"),  callback_data=\"quality:720:\"   + token)\n"
    "    builder.button(text=t(lang, \"btn_480p\"),  callback_data=\"quality:480:\"   + token)\n"
    "    builder.button(text=t(lang, \"btn_360p\"),  callback_data=\"quality:360:\"   + token)\n"
    "    builder.button(text=t(lang, \"btn_144p\"),  callback_data=\"quality:144:\"   + token)\n"
    "    builder.button(text=t(lang, \"btn_audio\"), callback_data=\"quality:audio:\" + token)\n"
    "    builder.adjust(2)\n"
    "    return builder.as_markup()\n"
    "\n"
    "\n"
    "def cancel_keyboard(user_id: int, lang: str = \"en\") -> InlineKeyboardMarkup:\n"
    "    builder = InlineKeyboardBuilder()\n"
    "    builder.button(text=t(lang, \"btn_cancel\"), callback_data=\"cancel:\" + str(user_id))\n"
    "    return builder.as_markup()\n"
)

# ── handlers/language.py ──────────────────────────────────────────────────────
files["handlers/language.py"] = (
    "from __future__ import annotations\n"
    "\n"
    "import logging\n"
    "\n"
    "from aiogram import Router, F\n"
    "from aiogram.filters import Command\n"
    "from aiogram.types import CallbackQuery, InlineKeyboardMarkup, Message\n"
    "from aiogram.utils.keyboard import InlineKeyboardBuilder\n"
    "\n"
    "from services.user_store import set_user_lang, get_user_lang_or_default\n"
    "from utils.i18n import t\n"
    "\n"
    "logger = logging.getLogger(__name__)\n"
    "router = Router(name=\"language\")\n"
    "\n"
    "\n"
    "def language_keyboard() -> InlineKeyboardMarkup:\n"
    "    builder = InlineKeyboardBuilder()\n"
    "    builder.button(text=\"English \U0001f1fa\U0001f1f8\",  callback_data=\"setlang:en\")\n"
    "    builder.button(text=\"\u0627\u0644\u0639\u0631\u0628\u064a\u0629 \U0001f1f5\U0001f1f8\",  callback_data=\"setlang:ar\")\n"
    "    builder.button(text=\"\u0420\u0443\u0441\u0441\u043a\u0438\u0439 \U0001f1f7\U0001f1fa\",  callback_data=\"setlang:ru\")\n"
    "    builder.adjust(1)\n"
    "    return builder.as_markup()\n"
    "\n"
    "\n"
    "@router.message(Command(\"language\"))\n"
    "async def cmd_language(message: Message) -> None:\n"
    "    await message.answer(\n"
    "        t(None, \"choose_language\"),\n"
    "        reply_markup=language_keyboard(),\n"
    "    )\n"
    "\n"
    "\n"
    "@router.callback_query(F.data.startswith(\"setlang:\"))\n"
    "async def cb_set_language(callback: CallbackQuery) -> None:\n"
    "    await callback.answer()\n"
    "    lang = (callback.data or \"\").split(\":\", 1)[1]\n"
    "    if lang not in (\"en\", \"ar\", \"ru\"):\n"
    "        return\n"
    "    user_id = callback.from_user.id\n"
    "    set_user_lang(user_id, lang)\n"
    "    try:\n"
    "        await callback.message.delete()\n"
    "    except Exception:\n"
    "        pass\n"
    "    await callback.message.answer(t(lang, \"language_changed\"))\n"
    "    await callback.message.answer(t(lang, \"welcome\"), parse_mode=\"Markdown\")\n"
)

# ── handlers/commands.py ──────────────────────────────────────────────────────
files["handlers/commands.py"] = (
    "from __future__ import annotations\n"
    "\n"
    "import logging\n"
    "\n"
    "from aiogram import Router\n"
    "from aiogram.filters import Command\n"
    "from aiogram.types import Message\n"
    "\n"
    "from config.settings import settings\n"
    "from services import cancel_download, stats\n"
    "from services.user_store import get_user_lang_or_default, has_chosen_language, register_user\n"
    "from handlers.language import language_keyboard\n"
    "from utils.i18n import t\n"
    "\n"
    "logger = logging.getLogger(__name__)\n"
    "router = Router(name=\"commands\")\n"
    "\n"
    "\n"
    "@router.message(Command(\"start\"))\n"
    "async def cmd_start(message: Message) -> None:\n"
    "    user_id = message.from_user.id\n"
    "    register_user(user_id)\n"
    "    if not has_chosen_language(user_id):\n"
    "        await message.answer(t(None, \"choose_language\"), reply_markup=language_keyboard())\n"
    "        return\n"
    "    lang = get_user_lang_or_default(user_id)\n"
    "    await message.answer(t(lang, \"welcome\"), parse_mode=\"Markdown\")\n"
    "\n"
    "\n"
    "@router.message(Command(\"help\"))\n"
    "async def cmd_help(message: Message) -> None:\n"
    "    lang = get_user_lang_or_default(message.from_user.id)\n"
    "    await message.answer(t(lang, \"help\"), parse_mode=\"Markdown\")\n"
    "\n"
    "\n"
    "@router.message(Command(\"quality\"))\n"
    "async def cmd_quality(message: Message) -> None:\n"
    "    lang = get_user_lang_or_default(message.from_user.id)\n"
    "    await message.answer(t(lang, \"quality_options\"), parse_mode=\"Markdown\")\n"
    "\n"
    "\n"
    "@router.message(Command(\"cancel\"))\n"
    "async def cmd_cancel(message: Message) -> None:\n"
    "    user_id = message.from_user.id\n"
    "    lang = get_user_lang_or_default(user_id)\n"
    "    if cancel_download(user_id):\n"
    "        await message.answer(t(lang, \"cancel_requested\"))\n"
    "    else:\n"
    "        await message.answer(t(lang, \"no_active_download\"))\n"
    "\n"
    "\n"
    "@router.message(Command(\"stats\"))\n"
    "async def cmd_stats(message: Message) -> None:\n"
    "    user_id = message.from_user.id\n"
    "    if settings.admin_id and user_id != settings.admin_id:\n"
    "        await message.answer(\"This command is only available to the bot administrator.\")\n"
    "        return\n"
    "    snapshot = await stats.get_snapshot()\n"
    "    lines = [\n"
    "        \"Sandy Squirrel - Statistics\",\n"
    "        \"\",\n"
    "        \"Uptime: \" + snapshot[\"uptime\"],\n"
    "        \"Successful: \" + str(snapshot[\"total_downloads\"]),\n"
    "        \"Failed: \" + str(snapshot[\"failed_downloads\"]),\n"
    "        \"Users: \" + str(snapshot[\"unique_users\"]),\n"
    "    ]\n"
    "    await message.answer(\"\\n\".join(lines))\n"
)

# ── handlers/callbacks.py ─────────────────────────────────────────────────────
files["handlers/callbacks.py"] = (
    "from __future__ import annotations\n"
    "\n"
    "import logging\n"
    "\n"
    "from aiogram import Bot, Router, F\n"
    "from aiogram.types import CallbackQuery\n"
    "\n"
    "from services.user_store import get_user_lang_or_default\n"
    "from utils import extract_url_from_text, is_valid_url\n"
    "from utils.i18n import t\n"
    "from handlers.common import resolve_url\n"
    "\n"
    "logger = logging.getLogger(__name__)\n"
    "router = Router(name=\"callbacks\")\n"
    "\n"
    "\n"
    "@router.callback_query(F.data.startswith(\"quality:\"))\n"
    "async def cb_quality(callback: CallbackQuery, bot: Bot) -> None:\n"
    "    await callback.answer()\n"
    "    user_id = callback.from_user.id\n"
    "    lang = get_user_lang_or_default(user_id)\n"
    "    parts = (callback.data or \"\").split(\":\", 2)\n"
    "    if len(parts) < 3:\n"
    "        await callback.message.answer(t(lang, \"invalid_selection\"))\n"
    "        return\n"
    "    _, quality, token = parts\n"
    "    url = resolve_url(token)\n"
    "    if not url:\n"
    "        url = extract_url_from_text(token) or token.strip()\n"
    "    if not is_valid_url(url):\n"
    "        await callback.message.answer(t(lang, \"expired_url\"))\n"
    "        return\n"
    "    audio_only = quality == \"audio\"\n"
    "    effective_quality = \"best\" if audio_only else quality\n"
    "    try:\n"
    "        await callback.message.delete()\n"
    "    except Exception:\n"
    "        pass\n"
    "    from handlers.downloader_handler import _run_download\n"
    "    await _run_download(\n"
    "        message=callback.message,\n"
    "        bot=bot,\n"
    "        url=url,\n"
    "        quality=effective_quality,\n"
    "        audio_only=audio_only,\n"
    "        user_id=user_id,\n"
    "    )\n"
    "\n"
    "\n"
    "@router.callback_query(F.data.startswith(\"cancel:\"))\n"
    "async def cb_cancel(callback: CallbackQuery) -> None:\n"
    "    user_id = callback.from_user.id\n"
    "    lang = get_user_lang_or_default(user_id)\n"
    "    await callback.answer(t(lang, \"cancelling\"))\n"
    "    from services import cancel_download\n"
    "    cancel_download(user_id)\n"
    "    try:\n"
    "        await callback.message.edit_text(t(lang, \"download_cancelled\"))\n"
    "    except Exception:\n"
    "        pass\n"
)

# ── handlers/downloader_handler.py ────────────────────────────────────────────
files["handlers/downloader_handler.py"] = (
    "from __future__ import annotations\n"
    "\n"
    "import logging\n"
    "\n"
    "from aiogram import Bot, Router, F\n"
    "from aiogram.filters import Command\n"
    "from aiogram.types import FSInputFile, Message\n"
    "\n"
    "from services import download_media, fetch_info, cleanup_session, stats\n"
    "from services.user_store import get_user_lang_or_default, register_user\n"
    "from utils import is_valid_url, detect_platform, extract_url_from_text, truncate, rate_limiter\n"
    "from utils.i18n import t\n"
    "from handlers.common import quality_keyboard\n"
    "\n"
    "logger = logging.getLogger(__name__)\n"
    "router = Router(name=\"downloader\")\n"
    "\n"
    "_active_downloads: set[int] = set()\n"
    "SMALL_FILE_LIMIT = 50 * 1024 * 1024\n"
    "\n"
    "\n"
    "async def _run_download(message, bot, url, quality=\"best\", audio_only=False, user_id=None):\n"
    "    if user_id is None:\n"
    "        user_id = message.from_user.id\n"
    "    lang = get_user_lang_or_default(user_id)\n"
    "    allowed, reason = await rate_limiter.check(user_id)\n"
    "    if not allowed:\n"
    "        await message.answer(reason)\n"
    "        return\n"
    "    if user_id in _active_downloads:\n"
    "        await message.answer(t(lang, \"active_download_warning\"))\n"
    "        return\n"
    "    _active_downloads.add(user_id)\n"
    "    status_msg = await message.answer(t(lang, \"fetching_info\"))\n"
    "    result = None\n"
    "    try:\n"
    "        try:\n"
    "            info = await fetch_info(url)\n"
    "        except ValueError as exc:\n"
    "            await status_msg.edit_text(t(lang, \"info_error\", error=str(exc)))\n"
    "            await stats.record_failure(user_id)\n"
    "            return\n"
    "        platform = detect_platform(url)\n"
    "        mode = \"Audio\" if audio_only else quality.upper()\n"
    "        preview = \"*\" + truncate(info.title, 80) + \"*\\n\" + info.uploader + \"\\n\" + info.duration + \"\\n\" + platform + \"\\n\\nDownloading \" + mode\n"
    "        await status_msg.edit_text(preview, parse_mode=\"Markdown\")\n"
    "        async def on_progress(msg_text):\n"
    "            try:\n"
    "                await status_msg.edit_text(msg_text)\n"
    "            except Exception:\n"
    "                pass\n"
    "        result = await download_media(\n"
    "            url=url, user_id=user_id, quality=quality,\n"
    "            audio_only=audio_only, progress_callback=on_progress,\n"
    "        )\n"
    "        if not result.success or not result.file_path:\n"
    "            await status_msg.edit_text(result.error or t(lang, \"download_failed\"))\n"
    "            await stats.record_failure(user_id)\n"
    "            return\n"
    "        await status_msg.edit_text(t(lang, \"uploading\"))\n"
    "        caption = \"*\" + truncate(result.info.title, 60) + \"*\\n\" + result.info.uploader + \"  |  \" + result.info.duration + \"  |  \" + result.info.file_size_str\n"
    "        actual_size = result.file_path.stat().st_size\n"
    "        try:\n"
    "            if actual_size > SMALL_FILE_LIMIT:\n"
    "                from services.telethon_uploader import upload_large_file\n"
    "                await upload_large_file(\n"
    "                    chat_id=message.chat.id, file_path=result.file_path,\n"
    "                    caption=caption, is_audio=audio_only,\n"
    "                )\n"
    "            else:\n"
    "                file_input = FSInputFile(result.file_path)\n"
    "                if audio_only or result.file_path.suffix.lower() == \".mp3\":\n"
    "                    await bot.send_audio(\n"
    "                        chat_id=message.chat.id, audio=file_input,\n"
    "                        caption=caption, parse_mode=\"Markdown\",\n"
    "                        title=result.info.title, performer=result.info.uploader,\n"
    "                    )\n"
    "                else:\n"
    "                    await bot.send_video(\n"
    "                        chat_id=message.chat.id, video=file_input,\n"
    "                        caption=caption, parse_mode=\"Markdown\",\n"
    "                        supports_streaming=True,\n"
    "                    )\n"
    "            await status_msg.delete()\n"
    "            await stats.record_success(user_id)\n"
    "        except Exception as exc:\n"
    "            logger.error(\"Upload error: %s\", exc)\n"
    "            await status_msg.edit_text(t(lang, \"upload_failed\", error=str(exc)))\n"
    "            await stats.record_failure(user_id)\n"
    "    except Exception as exc:\n"
    "        logger.exception(\"Unexpected error in _run_download\")\n"
    "        await status_msg.edit_text(t(lang, \"unexpected_error\", error=str(exc)))\n"
    "        await stats.record_failure(user_id)\n"
    "    finally:\n"
    "        _active_downloads.discard(user_id)\n"
    "        if result is not None and result.file_path:\n"
    "            cleanup_session(result.file_path)\n"
    "\n"
    "\n"
    "@router.message(Command(\"download\"))\n"
    "async def cmd_download(message: Message, bot: Bot) -> None:\n"
    "    lang = get_user_lang_or_default(message.from_user.id)\n"
    "    text = message.text or \"\"\n"
    "    parts = text.split(maxsplit=1)\n"
    "    if len(parts) < 2 or not parts[1].strip():\n"
    "        await message.answer(t(lang, \"download_usage\"), parse_mode=\"Markdown\")\n"
    "        return\n"
    "    url = extract_url_from_text(parts[1])\n"
    "    if not url:\n"
    "        await message.answer(t(lang, \"invalid_url\"))\n"
    "        return\n"
    "    await message.answer(\n"
    "        t(lang, \"choose_quality\", url=truncate(url, 60)),\n"
    "        parse_mode=\"Markdown\",\n"
    "        reply_markup=quality_keyboard(url, lang=lang),\n"
    "    )\n"
    "\n"
    "\n"
    "@router.message(Command(\"audio\"))\n"
    "async def cmd_audio(message: Message, bot: Bot) -> None:\n"
    "    lang = get_user_lang_or_default(message.from_user.id)\n"
    "    text = message.text or \"\"\n"
    "    parts = text.split(maxsplit=1)\n"
    "    if len(parts) < 2 or not parts[1].strip():\n"
    "        await message.answer(t(lang, \"audio_usage\"), parse_mode=\"Markdown\")\n"
    "        return\n"
    "    url = extract_url_from_text(parts[1])\n"
    "    if not url:\n"
    "        await message.answer(t(lang, \"invalid_url\"))\n"
    "        return\n"
    "    await _run_download(message, bot, url, audio_only=True)\n"
    "\n"
    "\n"
    "@router.message(F.text & F.text.regexp(r\"https?://\\S+\"))\n"
    "async def handle_url_message(message: Message, bot: Bot) -> None:\n"
    "    register_user(message.from_user.id)\n"
    "    lang = get_user_lang_or_default(message.from_user.id)\n"
    "    url = extract_url_from_text(message.text or \"\")\n"
    "    if not url or not is_valid_url(url):\n"
    "        return\n"
    "    await message.answer(\n"
    "        t(lang, \"link_detected\", url=truncate(url, 70)),\n"
    "        parse_mode=\"Markdown\",\n"
    "        reply_markup=quality_keyboard(url, lang=lang),\n"
    "    )\n"
)

# ── handlers/admin.py ─────────────────────────────────────────────────────────
files["handlers/admin.py"] = (
    "from __future__ import annotations\n"
    "\n"
    "import asyncio\n"
    "import logging\n"
    "\n"
    "from aiogram import Bot, Router\n"
    "from aiogram.filters import Command\n"
    "from aiogram.types import Message\n"
    "\n"
    "from config.settings import settings\n"
    "from services.user_store import get_all_user_ids, user_count\n"
    "\n"
    "logger = logging.getLogger(__name__)\n"
    "router = Router(name=\"admin\")\n"
    "\n"
    "\n"
    "def _is_admin(user_id: int) -> bool:\n"
    "    return bool(settings.admin_id) and user_id == settings.admin_id\n"
    "\n"
    "\n"
    "@router.message(Command(\"users\"))\n"
    "async def cmd_users(message: Message) -> None:\n"
    "    if not _is_admin(message.from_user.id):\n"
    "        return\n"
    "    total = user_count()\n"
    "    await message.answer(\n"
    "        \"<b>User Statistics</b>\\n\\n\"\n"
    "        \"Total registered users: <b>\" + str(total) + \"</b>\"\n"
    "    )\n"
    "\n"
    "\n"
    "@router.message(Command(\"broadcast\"))\n"
    "async def cmd_broadcast(message: Message, bot: Bot) -> None:\n"
    "    if not _is_admin(message.from_user.id):\n"
    "        return\n"
    "    text = message.text or \"\"\n"
    "    parts = text.split(maxsplit=1)\n"
    "    if len(parts) < 2 or not parts[1].strip():\n"
    "        await message.answer(\n"
    "            \"<b>Broadcast Usage</b>\\n\\n\"\n"
    "            \"<code>/broadcast Your message here</code>\\n\\n\"\n"
    "            \"Sends to all registered users.\\n\"\n"
    "            \"Current users: <b>\" + str(user_count()) + \"</b>\"\n"
    "        )\n"
    "        return\n"
    "    broadcast_text = parts[1].strip()\n"
    "    user_ids = get_all_user_ids()\n"
    "    if not user_ids:\n"
    "        await message.answer(\"No users to broadcast to yet.\")\n"
    "        return\n"
    "    status = await message.answer(\n"
    "        \"Broadcasting to <b>\" + str(len(user_ids)) + \"</b> users...\"\n"
    "    )\n"
    "    sent = 0\n"
    "    failed = 0\n"
    "    for uid in user_ids:\n"
    "        try:\n"
    "            await bot.send_message(uid, broadcast_text)\n"
    "            sent += 1\n"
    "        except Exception:\n"
    "            failed += 1\n"
    "        await asyncio.sleep(0.05)\n"
    "    await status.edit_text(\n"
    "        \"<b>Broadcast complete</b>\\n\\n\"\n"
    "        \"Sent: <b>\" + str(sent) + \"</b>\\n\"\n"
    "        \"Failed (blocked/deleted): <b>\" + str(failed) + \"</b>\"\n"
    "    )\n"
)

# ── handlers/__init__.py ──────────────────────────────────────────────────────
files["handlers/__init__.py"] = (
    "from aiogram import Router\n"
    "from handlers.commands import router as commands_router\n"
    "from handlers.language import router as language_router\n"
    "from handlers.downloader_handler import router as downloader_router\n"
    "from handlers.callbacks import router as callbacks_router\n"
    "from handlers.admin import router as admin_router\n"
    "\n"
    "main_router = Router(name=\"main\")\n"
    "main_router.include_router(commands_router)\n"
    "main_router.include_router(language_router)\n"
    "main_router.include_router(admin_router)\n"
    "main_router.include_router(callbacks_router)\n"
    "main_router.include_router(downloader_router)\n"
    "\n")