"""
services/telethon_uploader.py – Large file uploader using Telethon (up to 2GB)

Requires these env vars to be set:
  API_ID           – Telegram API ID (from my.telegram.org)
  API_HASH         – Telegram API Hash (from my.telegram.org)
  TELETHON_SESSION – Session string generated by generate_session.py

If any of these are missing, upload_large_file() raises a RuntimeError with
a clear message instead of crashing with a confusing Telethon error.
"""
from __future__ import annotations

import logging
import os
from pathlib import Path

from config.settings import settings

logger = logging.getLogger(__name__)

# Session string stored in env to avoid file system dependency on Railway
_SESSION_STRING = os.getenv("TELETHON_SESSION", "")

_client = None


def _telethon_configured() -> bool:
    """Return True only if all required Telethon env vars are present."""
    return bool(settings.api_id and settings.api_hash and _SESSION_STRING)


async def get_client():
    """Return an authenticated Telethon client (singleton)."""
    global _client

    if not _telethon_configured():
        raise RuntimeError(
            "Telethon is not configured. Set API_ID, API_HASH, and "
            "TELETHON_SESSION environment variables to enable large file uploads. "
            "Run generate_session.py to create a session string."
        )

    # Import lazily so missing Telethon install doesn't crash the whole bot
    from telethon import TelegramClient
    from telethon.sessions import StringSession

    if _client and _client.is_connected():
        return _client

    _client = TelegramClient(
        StringSession(_SESSION_STRING),
        settings.api_id,
        settings.api_hash,
    )

    await _client.connect()

    if not await _client.is_user_authorized():
        logger.error("Telethon client is not authorized. Run generate_session.py first.")
        raise RuntimeError("Telethon session not authorized.")

    return _client


async def upload_large_file(
    chat_id: int,
    file_path: Path,
    caption: str,
    is_audio: bool = False,
) -> None:
    """
    Upload a file up to 2GB via Telethon user account.

    Raises RuntimeError with a user-friendly message if Telethon is not
    configured, so the caller can show a proper error to the user instead
    of crashing.
    """
    if not _telethon_configured():
        raise RuntimeError(
            "⚠️ This file is larger than 50 MB and requires Telethon to upload, "
            "but Telethon is not configured on this server.\n\n"
            "To enable large file support, set these environment variables:\n"
            "• API_ID\n"
            "• API_HASH\n"
            "• TELETHON_SESSION\n\n"
            "Run generate_session.py locally to create the session string, "
            "then add it to your Railway environment."
        )

    client = await get_client()

    # Resolve numeric chat_id for Telethon
    entity = await client.get_entity(chat_id)

    file_size = file_path.stat().st_size
    logger.info("Starting Telethon upload: %s (%.1f MB)", file_path.name, file_size / 1024 / 1024)

    def _progress(sent, total):
        pct = (sent / total * 100) if total else 0
        logger.info("Upload progress: %.1f%% (%d / %d bytes)", pct, sent, total)

    if is_audio:
        await client.send_file(
            entity,
            str(file_path),
            caption=caption,
            voice=False,
            attributes=[],
            progress_callback=_progress,
        )
    else:
        await client.send_file(
            entity,
            str(file_path),
            caption=caption,
            supports_streaming=True,
            progress_callback=_progress,
        )

    logger.info("✅ Large file uploaded via Telethon: %s", file_path.name)